variable "aws_region" { default = "us-east-1" }
variable "image_prefix" { description = "Docker image URI prefix (registry/repo without tag)" }
variable "keeper_image" { description = "Keeper Docker image tag" }
variable "api_image" { description = "API Docker image tag" }
variable "sui_rpc_url" { default = "https://fullnode.testnet.sui.io:443" }
variable "package_id" { description = "Deployed contract package ID" }
variable "system_object_id" { description = "Walrus System object ID" }
variable "wal_coin_type" { description = "WAL coin type identifier" }
variable "database_url" { description = "PostgreSQL connection string" }
variable "db_username" { default = "walwatch" }
variable "db_password" { sensitive = true }
variable "subnet_ids" { description = "VPC subnet IDs for ECS" }
variable "vpc_id" { description = "VPC ID for ALB security group" }
variable "certificate_arn" { description = "ACM certificate ARN for ALB HTTPS listener" }
variable "alarm_notification_email" { default = "" }
variable "application_name" { default = "walwatch" }
variable "environment_name" { default = "production" }
variable "ecs_cluster_name" { default = "walwatch-keeper" }
variable "ecs_service_name" { default = "walwatch-keeper" }
variable "api_service_name" { default = "walwatch-api" }
